### ISSUE TITLE
ImportError on application start

### ISSUE THREAD

**Issue by tfeldmann** [zapisnicar/cookiecutter-pyside2#1]
I'm using the template with PySide2 and executed `make all` before starting:
```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from pyside2_demo import app
  File "/Users/tf/Desktop/PySide2_demo/pyside2_demo/app.py", line 13, in <module>
    from pyside2_demo.gui.mainwindow import Ui_MainWindow
  File "/Users/tf/Desktop/PySide2_demo/pyside2_demo/gui/mainwindow.py", line 104, in <module>
    import resources_rc
ModuleNotFoundError: No module named 'resources_rc'
```

**Comment by tfeldmann** [comment]
I think the error is that the `gui/mainwindow.py` file is compiled via `pyside2-uic` without the `--from-imports` flag.
So to fix this you could simply delete the `gui/mainwindow.py` file as `make` creates it automatically.

**Comment by zapisnicar** [comment]
I apologize for very, very late answer. I hope it is fixed now, thank you.

**Comment by tfeldmann** [comment]
No problem! Thanks for fixing 👍
